server:
  port: 8686

spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/travel_logs_db